apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels: { app: hello-app }
spec:
  type: LoadBalancer   # creates a public AWS load balancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-app
